#!/usr/bin/env sh

scriptdir=`dirname $0`
classpath="$scriptdir/lib/*"
DB_PATH=${DB_PATH:-/var/data/baasbox}

# check if the RUNNING_PID file exists. In this case it will be deleted if there is no process with the same PID stored in it
# RUNNING_PID file is created by BaasBox when it starts. If it quits unexpectedly (kill -9, server crash) the file is not deleted and BaasBox will not restarts
 
if [ -f /opt/baasbox/RUNNING_PID ];
then
	rm /opt/baasbox/RUNNING_PID
fi

exec java ${1+"$@"} -cp "$classpath" -Dorient.baasbox.path="${DB_PATH}" play.core.server.NettyServer `dirname $0`
